#[[main]]
  #name = "Demo"
  #url = "#hero"
  #weight = 10

[[main]]
  name = "Teaching"
  url = "#teaching"
  weight = 10
  

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 20


[[main]]
  name = "Students"
  url = "students/"
  weight = 30

#[[main]]
#  name = "Advising"
#  url = "advising3"
#  weight = 35
  
  
[[main]]
  name = "Pubs & Talks"
  url = "#talks"
  weight = 40
  
[[main]]
  name = "Blog"
  url = "#posts"
  weight = 50

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60
  
    

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
[[main]]
    name = "CV"
    url = "https://github.com/norcalbiostat/CV_Donatello.pdf"
    weight = 70
